//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAvanzada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego_Favorito
    {
        public string codigo_juego { get; set; }
        public string nombre_juego { get; set; }
        public string estrellas { get; set; }
    }
}
