//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAvanzada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lucha
    {
        public string codigo_l { get; set; }
        public string nombre_monstruo { get; set; }
        public string nombre_heroe { get; set; }
        public string resultado { get; set; }
        public string nombre_ganador { get; set; }
    
        public virtual Heroe Heroe { get; set; }
        public virtual Monstruo Monstruo { get; set; }
    }
}
